# one config per conversion (glodap2parquet, etc)
# config is read only by converters or downloaders (not by script)
# every converter needs a config file, no rogue arguments anymore

# CROCOLAKE
CROCOLAKE_PHY:
  db: CROCOLAKE
  db_type: PHY
  input_path: /home/enrico/myWHOI/CrocoLake/ctp-fork/scripts/data/parquet/PHY_CROCOLAKE_MERGED/2025-04-23/
  outdir_pq: /home/enrico/myWHOI/CrocoLake/ctp-fork/scripts/data/parquet/PHY_CROCOLAKE_MERGED/2025-04-23/
  outdir_schema: ./schema/
  fname_pq: PHY_CROCOLAKE_MERGED
  add_derived_vars: True
  overwrite: False
  tmp_path:
  ln_path: /home/enrico/myWHOI/CrocoLake/ctp-fork/scripts/data/parquet/PHY_CROCOLAKE_LN/

# Argo QC
ARGO_PHY:
  db: ARGO
  db_type: PHY
  input_path: ../demo/demo_ARGO_PQT_PHY/
  outdir_pq: ../demo/parquet/demo_ARGO-QC_PHY/
  outdir_schema: ./schema/
  fname_pq: demo_ARGO-QC_PHY
  add_derived_vars: True
  overwrite: False
  tmp_path:

ARGO_BGC:
  db: ARGO
  db_type: BGC
  input_path: ../demo/demo_ARGO_PQT_BGC/
  outdir_pq: ../demo/parquet/demo_ARGO-QC_BGC/
  outdir_schema: ./schema/
  fname_pq: demo_ARGO-QC_BGC
  add_derived_vars: True
  overwrite: False
  tmp_path:

# GLODAP config
GLODAP_PHY:
  db: GLODAP
  db_type: PHY
  input_path: ../demo/demo_GLODAP/
  outdir_pq: ../demo/parquet/demo_GLODAP_PHY/
  outdir_schema: ./schema/
  fname_pq: demo_GLODAP_PHY
  add_derived_vars: False
  overwrite: False
  tmp_path:

GLODAP_BGC:
  db: GLODAP
  db_type: BGC
  input_path: ../demo/demo_GLODAP/
  outdir_pq: ../demo/parquet/demo_GLODAP_BGC/
  outdir_schema: ./schema/
  fname_pq: demo_GLODAP_BGC
  add_derived_vars: True
  overwrite: False
  tmp_path:

# Spray Gliders
SprayGliders_PHY:
  db: SprayGliders
  db_type: PHY
  input_path: ../demo/demo_SPRAY_PHY/
  outdir_pq: ../demo/parquet/demo_SPRAY_PHY/
  outdir_schema: ./schemas/
  fname_pq: demo_SPRAY_PHY
  add_derived_vars: True
  overwrite: False
  tmp_path: ../demo/demo_tmp_SPRAY_PHY/

SprayGliders_BGC:
  db: SprayGliders
  db_type: BGC
  input_path: ../demo/demo_SPRAY_BGC/
  outdir_pq: ../demo/parquet/demo_SPRAY_BGC/
  outdir_schema: ./schemas/
  fname_pq: demo_SPRAY_BGC
  add_derived_vars: True
  overwrite: False
  tmp_path: ../demo/demo_tmp_SPRAY_BGC/
