# This config file contains the fields for the config dictionary required by the
# Converter class.
#
# DB_NAME_<DB_TYPE>
#   db: name of the database
#   db_type: (PHY or BGC)
#   input_path: path with original files to convert
#   outdir_pq: destination path for parquet version
#   outdir_schema: destination path for the schema of the parquet version
#   fname_pq: basename for the parquet file (e.g. 'filename' would generate 'filename_XXX.parquet' files)
#   add_derived_vars: True to add derived variables (absolute salinity, conservative temperature, sigma1)
#   overwrite: True to overwrite any pre-existing parquet dataset in outdir_pq
#   tmp_path: folder for temporary files (not required by all converters)
#   ln_path: path to symbolic links to generate CrocoLake (required only when generating CrocoLake with CrocoLakeLoader)


# CROCOLAKE
CROCOLAKE_PHY:
  db: CROCOLAKE
  db_type: PHY
  outdir_pq: ../demo/parquet/demo_CROCOLAKE_PHY/
  fname_pq: PHY_CROCOLAKE
  ln_path: ../demo/parquet/demo_CROCOLAKE_PHY_LN/

CROCOLAKE_BGC:
  db: CROCOLAKE
  db_type: BGC
  outdir_pq: ../demo/parquet/demo_CROCOLAKE_BGC/
  fname_pq: BGC_CROCOLAKE
  ln_path: ../demo/parquet/demo_CROCOLAKE_BGC_LN/

# Argo QC
ARGO_PHY:
  db: ARGO
  db_type: PHY
  input_path: ../demo/demo_ARGO_PQT_PHY/
  outdir_pq: ../demo/parquet/demo_ARGO-QC_PHY/
  outdir_schema: ./schema/
  fname_pq: demo_ARGO-QC_PHY
  add_derived_vars: True
  overwrite: False
  tmp_path:

ARGO_BGC:
  db: ARGO
  db_type: BGC
  input_path: ../demo/demo_ARGO_PQT_BGC/
  outdir_pq: ../demo/parquet/demo_ARGO-QC_BGC/
  outdir_schema: ./schema/
  fname_pq: demo_ARGO-QC_BGC
  add_derived_vars: True
  overwrite: False
  tmp_path:

# GLODAP config
GLODAP_PHY:
  db: GLODAP
  db_type: PHY
  input_path: ../demo/demo_GLODAP/
  outdir_pq: ../demo/parquet/demo_GLODAP_PHY/
  outdir_schema: ./schema/
  fname_pq: demo_GLODAP_PHY
  add_derived_vars: False
  overwrite: False
  tmp_path:

GLODAP_BGC:
  db: GLODAP
  db_type: BGC
  input_path: ../demo/demo_GLODAP/
  outdir_pq: ../demo/parquet/demo_GLODAP_BGC/
  outdir_schema: ./schema/
  fname_pq: demo_GLODAP_BGC
  add_derived_vars: True
  overwrite: False
  tmp_path:

# Spray Gliders
SprayGliders_PHY:
  db: SprayGliders
  db_type: PHY
  input_path: ../demo/demo_SPRAY_PHY/
  outdir_pq: ../demo/parquet/demo_SPRAY_PHY/
  outdir_schema: ./schemas/
  fname_pq: demo_SPRAY_PHY
  add_derived_vars: True
  overwrite: False
  tmp_path: ../demo/demo_tmp_SPRAY_PHY/

SprayGliders_BGC:
  db: SprayGliders
  db_type: BGC
  input_path: ../demo/demo_SPRAY_BGC/
  outdir_pq: ../demo/parquet/demo_SPRAY_BGC/
  outdir_schema: ./schemas/
  fname_pq: demo_SPRAY_BGC
  add_derived_vars: True
  overwrite: False
  tmp_path: ../demo/demo_tmp_SPRAY_BGC/

# Saildrones
Saildrones_PHY:
  db: Saildrones
  db_type: PHY
  input_path: ../demo/demo_Saildrones_PHY/
  outdir_pq: ../demo/parquet/demo_Saildrones_PHY/
  outdir_schema: ./schemas/Saildrones/
  fname_pq: demo_SAILDRONES_PHY
  add_derived_vars: True
  overwrite: True
  tmp_path:

Saildrones_BGC:
  db: Saildrones
  db_type: BGC
  input_path: ../demo/demo_Saildrones_BGC/
  outdir_pq: ../demo/parquet/demo_Saildrones_BGC/
  outdir_schema: ./schemas/Saildrones/
  fname_pq: demo_SAILDRONES_BGC
  add_derived_vars: True
  overwrite: True
  tmp_path: