# one config per conversion (glodap2parquet, etc)
# config is read only by converters or downloaders (not by script)
# every converter needs a config file, no rogue arguments anymore

# CROCOLAKE
CROCOLAKE_PHY:
  db: CROCOLAKE
  db_type: PHY
  input_path: /home/enrico/myWHOI/CrocoLake/ctp-fork/scripts/data/parquet/PHY_CROCOLAKE_MERGED/2025-04-23/
  outdir_pq: /home/enrico/myWHOI/CrocoLake/ctp-fork/scripts/data/parquet/PHY_CROCOLAKE_MERGED/2025-04-23/
  outdir_schema: ./schema/
  fname_pq: PHY_CROCOLAKE_MERGED
  add_derived_vars: True
  overwrite: False
  tmp_path:
  ln_path: /home/enrico/myWHOI/CrocoLake/ctp-fork/scripts/data/parquet/PHY_CROCOLAKE_LN/

# Argo QC
ARGO_PHY:
  db: ARGO
  db_type: PHY
  input_path: /home/enrico/myWHOI/CrocoLake/ctp-fork/scripts/data/parquet/PHY_ARGO-GDAC/2025-04-23/
  outdir_pq: /home/enrico/myWHOI/CrocoLake/ctp-fork/scripts/data/parquet/PHY_ARGO-QC/2025-04-24/
  outdir_schema: ./schema/
  fname_pq: PHY_ARGO-QC
  add_derived_vars: True
  overwrite: False
  tmp_path:

ARGO_BGC:
  db: ARGO
  db_type: BGC
  input_path: /home/enrico/myWHOI/CrocoLake/ctp-fork/scripts/data/parquet/BGC_ARGO-GDAC/2025-04-23/
  outdir_pq: /home/enrico/myWHOI/CrocoLake/ctp-fork/scripts/data/parquet/BGC_ARGO-QC/2025-04-23/
  outdir_schema: ./schema/
  fname_pq: BGC_ARGO-QC
  add_derived_vars: True
  overwrite: False
  tmp_path:

# GLODAP config
GLODAP_PHY:
  db: GLODAP
  db_type: PHY
  input_path: /home/enrico/myWHOI/databases/GLODAP/v2.2023/
  outdir_pq: /home/enrico/myWHOI/databases/GLODAP/v2.2023/parquet/
  outdir_schema: ./schema/
  fname_pq: 1101_PHY_GLODAP
  add_derived_vars: False
  overwrite: False
  tmp_path:

GLODAP_BGC:
  db: GLODAP
  db_type: BGC
  input_path: /home/enrico/myWHOI/databases/GLODAP/v2.2023/
  outdir_pq: /home/enrico/myWHOI/databases/GLODAP/v2.2023/parquet_bgc/
  outdir_schema: ./schema/
  fname_pq: 1101_BGC_GLODAP
  add_derived_vars: True
  overwrite: False
  tmp_path:

# Spray Gliders
SprayGliders_PHY:
  db: SprayGliders
  db_type: PHY
  input_path: /home/enrico/myWHOI/databases/Spray_Glider/projects
  outdir_pq: /home/enrico/myWHOI/databases/Spray_Glider/parquet/
  outdir_schema: ./schemas/
  fname_pq: 1201_PHY_SPRAY
  add_derived_vars: True
  overwrite: False
  tmp_path:

SprayGliders_BGC:
  db: SprayGliders
  db_type: BGC
  input_path: /home/enrico/myWHOI/databases/Spray_Glider/projects
  outdir_pq:
  outdir_schema: ./schemas/
  fname_pq: 1201_BGC_SPRAY
  add_derived_vars: True
  overwrite: False
  tmp_path:
