# This config file contains the fields for the config_hpc dictionary used by the
# scripts in the script folder.
# Field names must be arguments to dask's LocalCluster Client
#  (https://docs.dask.org/en/stable/deploying-python.html)


# Argo
ARGO-QC_PHY:
    threads_per_worker: 1
    n_workers: 18
    memory_limit: 'auto'
    processes: True

ARGO-QC_BGC:
    threads_per_worker: 9
    n_workers: 4
    memory_limit: '36GiB' # memory limit per worker
    processes: True

SPRAY_GLIDERS:
    threads_per_worker: 20
    n_workers: 1
    memory_limit: '110GB'
    processes: True

# Saildrones configuration
SAILDRONES:
    threads_per_worker: 8
    n_workers: 2
    memory_limit: '32GB'
    processes: True